//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCommerciale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Categories
    {
        public int Id { get; set; }
        public string Cat_Name { get; set; }
        public byte[] Cat_img { get; set; }
    }
}
